theme: jekyll-theme-slate
title: "Expert CyberSecurité & DevSecOps : Développer, PenTester et Déployer des applications sécurisées"
description: "Devenir Spécialiste CyberSecurité & DevSecOps : Comprendre les risques d’une application pour prioriser les tests et les corrections ; Réaliser un PenTest appli"
url: "https://www.ilaria-academy.com/nextjob/appsec-cybersecurity-hacker/fr/"
show_downloads: false
